name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install
      
      - name: Build project
        run: yarn build
        env:
          PORTFOLIO_SOURCE: ${{ secrets.PORTFOLIO_SOURCE }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_18208 }}'
          channelId: live
          projectId: portfolio-18208
